a=input('Enter The Value1:-')
b=input('Enter he Value2:-')
print(a+b)
print('Type costing (int) use karenge user input int ko int me lene ke liye or convert Example ')
a=int(input('Enter The Value1:-'))
b=int(input('Enter The Value2:-'))
print(a+b)
print('Float type casting use kar float me convert')
a=float(input('Enter The Vlue1:-'))
b=float(input('Enter The Value2:-'))
print(a+b)
print('eval type casting use karnge because every input by user finding input function')
a=eval(input('Enter The Value1:-'))
b=eval(input('Enter The Value2:-'))
print(a+b)
a=eval(input('Enter The Value1:-'))
b=eval(input('Enter The Value2:-'))
print(a+b)

